// Original categories from flzr.com/references/, 16 September 2026.
// IDs match the verbatim content import; unrelated cases have no category.
export const REFERENCE_CATEGORIES: Record<string, string> = {
  "7dbf1a02-91d6-4e57-93d5-d378c7ec02f8": "Consumer Electronics",
  "case-flizr-o2-studio-en": "Consumer Electronics",
  "case-flzr-reference-03-en": "Consumer Electronics",
  "case-flzr-reference-04-en": "Consumer Electronics",
  "case-flizr-bose-q4-en": "Consumer Electronics",
  "case-flzr-reference-06-en": "Consumer Electronics",
  "case-flzr-reference-07-en": "Consumer Electronics",
  "case-flzr-reference-08-en": "Consumer Electronics",
  "case-flzr-reference-09-en": "Consumer Electronics",
  "case-flzr-reference-10-en": "Consumer Electronics",
  "case-flzr-reference-11-en": "Consumer Electronics",
  "case-flzr-reference-12-en": "DIY & Household",
  "case-flzr-reference-13-en": "DIY & Household",
  "case-flzr-reference-14-en": "DIY & Household",
  "case-flzr-reference-15-en": "DIY & Household",
  "case-flzr-reference-16-en": "DIY & Household",
  "case-flzr-reference-17-en": "DIY & Household",
  "case-flzr-reference-18-en": "DIY & Household",
  "case-flzr-reference-19-en": "Food",
  "case-flzr-reference-20-en": "Food",
  "case-flzr-reference-21-en": "Food",
  "case-flzr-reference-22-en": "Food",
  "case-flzr-reference-23-en": "Food",
  "case-flzr-reference-24-en": "Beauty & Fashion",
  "case-flzr-reference-25-en": "Beauty & Fashion",
  "case-flzr-reference-26-en": "Beauty & Fashion",
  "case-flzr-reference-27-en": "Beauty & Fashion",
  "case-flzr-reference-28-en": "Beauty & Fashion",
  "case-flzr-reference-29-en": "Toys",
  "case-flzr-reference-30-en": "Toys",
  "case-flzr-reference-31-en": "Toys",
  "case-flzr-reference-32-en": "Toys",
  "case-flzr-reference-33-en": "Toys"
};
