import { type SchemaTypeDefinition } from 'sanity'
import page from './page'
import menu from './Global/components/menu'
import caseStudy from './Global/Cases/caseStudy'
import unitCase from './Global/Cases/unitCase'
import client from './Global/Cases/client'
import person from './Global/Cases/person'
import { OneSPschemaTypes } from './1spContent'
import { FLZRschemaTypes } from './flzrContent'
import { CaseStudySchemaTypes } from './caseStudyContent'
import { MSMschemaTypes } from './msmContent'
import link from './Global/Objects/link'
import cta from './Global/Objects/cta'
import paragraph from './Global/Objects/paragraph'
import size from './Global/Objects/size'
import services from './Global/Objects/services'
import serviceGroup from './Global/Objects/serviceGroup'
import cloudinaryImage from './Global/Objects/cloudinaryImage'
import mediaGalleryItem from './Global/Objects/mediaGalleryItem'
import imageGalleryItem from './Global/Objects/imageGalleryItem'
import personReference from './Global/Objects/personReference'
import clientReference from './Global/Objects/clientReference'
import metadata from './Global/Objects/metadata'
import contactForm from './Global/Objects/contactForm'
import contactSubmission from './Global/contactSubmission'
import oneSpComponentGroup from './Global/oneSpComponentGroup'
import oneSpComponentGroupReference from './Global/Objects/oneSpComponentGroupReference'
import translationGuidelines from './Global/translationGuidelines'
import siteSettings from './Global/siteSettings'
import renaissanceSectionBand from './RENAISSANCE/Components/renaissanceSectionBand'

export const schema: { types: SchemaTypeDefinition[] } = {
  types: [page, menu, siteSettings, oneSpComponentGroup, translationGuidelines, caseStudy, unitCase, client, person, contactSubmission, ...OneSPschemaTypes, ...FLZRschemaTypes, ...CaseStudySchemaTypes, ...MSMschemaTypes, renaissanceSectionBand, link, cta, paragraph, size, services, serviceGroup, cloudinaryImage, mediaGalleryItem, imageGalleryItem, personReference, clientReference, metadata, contactForm, oneSpComponentGroupReference],
}
